#!/bin/bash
#
# Intro exercise from https://tutorialspoint.com/unix/shell_scripting.htm

# Prompt the user for input and store the input in a variable
printf 'What is your name?\n'
read name
printf "Hello, $name.\n"

