#!/bin/bash
#
# Specal variable exercises from
# https://www.tutorialspoint.com/unix/unix-special-variables.htm

printf '$0 - filename of the current script\n'
printf "$0\n\n"

printf '$1 - $n is the nth argument to the script\n'
printf "$1\n\n"

printf '$# - the number of arguments to the script\n'
printf "$#\n\n"

printf '$* - if double quoted, all the arguments to the script as one string\n'
printf '     otherwise, all the arguments to the script as separate strings\n'

for token in "$*"; do
  printf "\"\$*\": ${token}\n"
done

for token in $*; do
  printf "\$*: ${token}\n"
done

printf '\n'

printf '$@ - all of the arguments to the script as separate strings\n'

for token in "$@"; do
  printf "\"\$@\": ${token}\n"
done

for token in $@; do
  printf "\$@: ${token}\n"
done

printf '\n'

printf '$? - exit code of the last command\n'
false
printf "false -> $?\n\n"

printf '$$ - process ID (PID) of the current shell\n'
printf "$$\n\n"

printf '$! - PID of the last background command\n'
sleep 0 &
printf "sleep 0 & -> $!\n"

